#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

from thrift.Thrift import *

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class ExceptionCode:
  PROCESSING = 1
  ENCODING = 2
  GENERIC = 3

  _VALUES_TO_NAMES = {
    1: "PROCESSING",
    2: "ENCODING",
    3: "GENERIC",
  }

  _NAMES_TO_VALUES = {
    "PROCESSING": 1,
    "ENCODING": 2,
    "GENERIC": 3,
  }

class ExtractorType:
  DEFAULT = 1
  ARTICLE = 2
  CANOLA = 3
  ARTICLE_SENTENCE = 4
  DEBUG = 5

  _VALUES_TO_NAMES = {
    1: "DEFAULT",
    2: "ARTICLE",
    3: "CANOLA",
    4: "ARTICLE_SENTENCE",
    5: "DEBUG",
  }

  _NAMES_TO_VALUES = {
    "DEFAULT": 1,
    "ARTICLE": 2,
    "CANOLA": 3,
    "ARTICLE_SENTENCE": 4,
    "DEBUG": 5,
  }


class ExtractorException(Exception):
  """
  Attributes:
   - code
   - message
   - trace
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'code', None, None, ), # 1
    (2, TType.STRING, 'message', None, None, ), # 2
    (3, TType.STRING, 'trace', None, None, ), # 3
  )

  def __init__(self, code=None, message=None, trace=None,):
    self.code = code
    self.message = message
    self.trace = trace

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.code = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.message = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.trace = iprot.readString().decode('utf-8')
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('ExtractorException')
    if self.code != None:
      oprot.writeFieldBegin('code', TType.I32, 1)
      oprot.writeI32(self.code)
      oprot.writeFieldEnd()
    if self.message != None:
      oprot.writeFieldBegin('message', TType.STRING, 2)
      oprot.writeString(self.message.encode('utf-8'))
      oprot.writeFieldEnd()
    if self.trace != None:
      oprot.writeFieldBegin('trace', TType.STRING, 3)
      oprot.writeString(self.trace.encode('utf-8'))
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()
    def validate(self):
      return


  def __str__(self):
    return repr(self)

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
